import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import LayoutWrapper from "@/components/shared/LayoutWrapper";
import Providers from "@/providers/Providers";
import { getServerSession } from "next-auth";
import { authOptions } from "@/utils/authOptions";

const geistInter = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Upload Games",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  // console.log("session", session);
  return (
    <html lang="en">
      <body
        className={`${geistInter.variable} antialiased border border-red-600 ovh`}
      >
        <Providers>
          <LayoutWrapper session={session}>{children}</LayoutWrapper>
        </Providers>
        <Toaster position="top-right" />
      </body>
    </html>
  );
}
