import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/shared/Footer";
import Navbar from "@/components/shared/Navbar";
import MobileNavbar from "@/components/shared/MobileNavbar";
import { Toaster } from "react-hot-toast";

const geistInter = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistInter.variable} antialiased`}>
        <div className=" min-h-screen flex flex-col">
          {/* Show Desktop Navbar on medium screens and up */}
          <div className="hidden md:block">
            <Navbar />
          </div>

          {/* Show Mobile Navbar on screens smaller than medium */}
          <div className="block md:hidden">
            <MobileNavbar />
          </div>
          {children}
          <Footer />
        </div>
        <Toaster />
      </body>
    </html>
  );
}
